import {
  DirectionEnum,
  RemedyTypeEnum,
  RoomTypeEnum,
  SeverityEnum,
  VerdictEnum,
} from '../../../common/constants/index.js';
import { VastuRuleDefinition } from '../types/vastu-rule.interface.js';

export const KITCHEN_RULES: ReadonlyArray<VastuRuleDefinition> = [
  {
    code: 'KIT-001-STOVE-SE',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'ELEMENTAL',
    name: 'Cooking Stove in South-East (Agni Corner)',
    description:
      'Cooking stove is situated in the South-East (Agneya) fire quadrant, maximizing metabolic vitality and prosperity.',
    targetObject: 'gas_stove',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.SOUTH_EAST,
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 15,
    defaultRemedy: 'Ideal placement. Maintain cleanliness around the burner.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'KIT-002-STOVE-NE-DEFECT',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'ELEMENTAL',
    name: 'Stove in North-East (Fire in Water Zone Defect)',
    description:
      'Gas stove is placed in the North-East (Ishanya) water zone. Fire in this sacred water zone creates financial instability and digestive friction.',
    targetObject: 'gas_stove',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.NORTH_EAST,
    },
    severity: SeverityEnum.CRITICAL,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -30,
    defaultRemedy:
      'Shift cooking appliance immediately towards South-East. If immovable, place a green marble or jade stone slab directly beneath the burner.',
    remedyType: RemedyTypeEnum.ELEMENTAL,
    isActive: true,
  },
  {
    code: 'KIT-003-SINK-NE',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'PLACEMENT',
    name: 'Water Sink in North or North-East',
    description:
      'Water sink and drainage are situated in the water-compatible North or North-East quadrant, facilitating healthy bio-energy.',
    targetObject: 'sink',
    condition: {
      field: 'zone',
      op: 'IN',
      value: [DirectionEnum.NORTH, DirectionEnum.NORTH_EAST],
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 10,
    defaultRemedy: 'Optimal placement for water drainage.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'KIT-004-FIRE-WATER-CLASH',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'ELEMENTAL',
    name: 'Stove Adjacent to Sink (Fire-Water Opposition)',
    description:
      'The gas stove and water sink are located in direct proximity (< 0.9m), generating constant elemental conflict between Agni (Fire) and Jal (Water).',
    targetObject: 'gas_stove',
    condition: {
      op: 'DISTANCE_LESS_THAN',
      targetObject: 'sink',
      maxMeters: 0.9,
    },
    severity: SeverityEnum.HIGH,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -20,
    defaultRemedy:
      'Introduce a wooden partition, wooden cutting board, or live green money plant between the stove and the sink to mediate fire and water.',
    remedyType: RemedyTypeEnum.ELEMENTAL,
    isActive: true,
  },
  {
    code: 'KIT-005-BED-IN-KITCHEN',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'ELEMENTAL',
    name: 'Bed or Sleeping Furniture in Kitchen Area',
    description:
      'A bed or sleeping furniture is situated inside the kitchen. In classical Vastu, sleeping in the Agni (fire) preparation space causes chronic restlessness, metabolic disruption, and severe energetic conflict.',
    targetObject: 'bed',
    condition: {
      field: 'objectType',
      op: 'EQUALS',
      value: 'bed',
    },
    severity: SeverityEnum.CRITICAL,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -30,
    defaultRemedy:
      'Relocate the bed immediately to a dedicated bedroom in the South-West or South quadrant. Never sleep inside or facing the cooking fire area.',
    remedyType: RemedyTypeEnum.STRUCTURAL,
    isActive: true,
  },
  {
    code: 'KIT-006-STOVE-CENTER-DEFECT',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'ELEMENTAL',
    name: 'Cooking Stove in Kitchen Center (Brahmasthan Defect)',
    description:
      'Cooking stove or open burner island is placed in the center (Brahmasthan) of the kitchen. Fire element in the cosmic core creates high domestic stress and energetic exhaustion.',
    targetObject: 'gas_stove',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.CENTER,
    },
    severity: SeverityEnum.CRITICAL,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -30,
    defaultRemedy:
      'Relocate cooking stove against the South-East wall. Keep the kitchen center open and unobstructed.',
    remedyType: RemedyTypeEnum.STRUCTURAL,
    isActive: true,
  },
  {
    code: 'KIT-007-STOVE-NORTH-DEFECT',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'ELEMENTAL',
    name: 'Cooking Stove in North (Fire in Water / Wealth Zone Defect)',
    description:
      'The cooking stove is placed in the North (Kuber / Jal) quadrant. Fire in the wealth-attracting water zone causes drain of financial resources, career obstacles, and elemental conflict.',
    targetObject: 'gas_stove',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.NORTH,
    },
    severity: SeverityEnum.HIGH,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -20,
    defaultRemedy:
      'Shift the cooking stove towards the South-East (Agni) quadrant. If structural movement is impossible, place a green marble or jade stone slab beneath the stove to mediate the fire and water elements.',
    remedyType: RemedyTypeEnum.ELEMENTAL,
    isActive: true,
  },
  {
    code: 'KIT-008-STOVE-SW-DEFECT',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'ELEMENTAL',
    name: 'Cooking Stove in South-West (Earth Stability Defect)',
    description:
      'The cooking stove is located in the South-West (Nirruthi) earth quadrant. Fire in the stability corner burns relationship harmony and induces emotional friction.',
    targetObject: 'gas_stove',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.SOUTH_WEST,
    },
    severity: SeverityEnum.HIGH,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -20,
    defaultRemedy:
      'Shift the stove towards the South-East. If immovable, use a yellow Jaisalmer stone platform beneath the stove to ground the earth element.',
    remedyType: RemedyTypeEnum.ELEMENTAL,
    isActive: true,
  },
  {
    code: 'KIT-009-STOVE-EAST-COMPLIANT',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'PLACEMENT',
    name: 'Cooking Stove in East (Surya Alignment)',
    description:
      'The cooking stove is situated in the East zone, allowing the cook to face East towards the morning sun, promoting family vitality and positivity.',
    targetObject: 'gas_stove',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.EAST,
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 10,
    defaultRemedy: 'Favorable cooking orientation. Keep the counter clean and well-illuminated.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'KIT-010-STOVE-NW-COMPLIANT',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'ELEMENTAL',
    name: 'Cooking Stove in North-West (Vayu Zone Alternative)',
    description:
      'The cooking stove is placed in the North-West (Vayu) quadrant. Air naturally supports fire, making this an acceptable classical alternative when South-East is unavailable.',
    targetObject: 'gas_stove',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.NORTH_WEST,
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 5,
    defaultRemedy: 'Acceptable secondary placement. Ensure ample kitchen ventilation.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'KIT-011-STOVE-SOUTH-COMPLIANT',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'ELEMENTAL',
    name: 'Cooking Stove in South (Agni Zone Extension)',
    description:
      'Stove positioned along the South wall, a natural extension of the Agni (Fire) zone. Promotes healthy metabolic vitality.',
    targetObject: 'gas_stove',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.SOUTH,
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 10,
    defaultRemedy:
      'Favorable cooking position. Ensure cook faces East while preparing food.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'KIT-012-STOVE-WEST-COMPLIANT',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'ELEMENTAL',
    name: 'Cooking Stove in West (Secondary Cooking Zone)',
    description:
      'Cooking stove situated along the West wall, an acceptable classical alternative for modern kitchens.',
    targetObject: 'gas_stove',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.WEST,
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 5,
    defaultRemedy:
      'Acceptable secondary placement. Cooking while facing East or North is recommended.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'KIT-013-FRIDGE-SW-COMPLIANT',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'PLACEMENT',
    name: 'Refrigerator Grounded in South-West or North-West',
    description:
      'Heavy refrigeration appliance placed in the South-West, West, or North-West sector, providing solid grounding for heavy kitchen equipment.',
    targetObject: 'refrigerator',
    condition: {
      field: 'zone',
      op: 'IN',
      value: [DirectionEnum.SOUTH_WEST, DirectionEnum.SOUTH, DirectionEnum.WEST, DirectionEnum.NORTH_WEST],
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 10,
    defaultRemedy:
      'Ideal refrigerator location. Maintain a 2-inch clearance from the wall for positive airflow.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'KIT-014-FRIDGE-NE-DEFECT',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'PLACEMENT',
    name: 'Refrigerator in North-East (Ishanya Blockage)',
    description:
      'Bulky cooling appliance situated in the sacred North-East (water) quadrant. Blocks subtle cosmic prana and causes metabolic or digestive sluggishness.',
    targetObject: 'refrigerator',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.NORTH_EAST,
    },
    severity: SeverityEnum.HIGH,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -15,
    defaultRemedy:
      'Shift refrigerator to the South-West or North-West zone of the kitchen.',
    remedyType: RemedyTypeEnum.STRUCTURAL,
    isActive: true,
  },
  {
    code: 'KIT-015-MICROWAVE-SE-COMPLIANT',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'ELEMENTAL',
    name: 'Microwave / Electric Oven in South-East (Agni Alignment)',
    description:
      'Electrical heating appliance placed in the South-East (Fire) quadrant, harmonizing electrical heat with cosmic Agni.',
    targetObject: 'microwave',
    condition: {
      field: 'zone',
      op: 'IN',
      value: [DirectionEnum.SOUTH_EAST, DirectionEnum.EAST, DirectionEnum.SOUTH],
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 10,
    defaultRemedy:
      'Optimal electrical alignment for cooking appliances.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'KIT-016-MICROWAVE-NE-DEFECT',
    roomType: RoomTypeEnum.KITCHEN,
    category: 'ELEMENTAL',
    name: 'Microwave / Oven in North-East (Fire-Water Conflict)',
    description:
      'Electrical heating appliance placed in the sacred North-East water zone. Generates elemental conflict between heat and water energy.',
    targetObject: 'microwave',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.NORTH_EAST,
    },
    severity: SeverityEnum.HIGH,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -15,
    defaultRemedy:
      'Relocate heating appliances to the South-East counter.',
    remedyType: RemedyTypeEnum.ELEMENTAL,
    isActive: true,
  },
];
