import {
  DirectionEnum,
  RemedyTypeEnum,
  RoomTypeEnum,
  SeverityEnum,
  VerdictEnum,
} from '../../../common/constants/index.js';
import { VastuRuleDefinition } from '../types/vastu-rule.interface.js';

export const LIVING_ROOM_RULES: ReadonlyArray<VastuRuleDefinition> = [
  {
    code: 'LIV-001-SOFA-SW',
    roomType: RoomTypeEnum.LIVING_ROOM,
    category: 'PLACEMENT',
    name: 'Heavy Sofa / Seating Grounded in South or South-West',
    description:
      'Heavy living room seating is positioned against the South or West walls, anchoring family stability and authority.',
    targetObject: 'sofa',
    condition: {
      field: 'zone',
      op: 'IN',
      value: [DirectionEnum.SOUTH_WEST, DirectionEnum.SOUTH, DirectionEnum.WEST],
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 10,
    defaultRemedy: 'Ideal configuration for living room seating.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'LIV-002-TV-NE-DEFECT',
    roomType: RoomTypeEnum.LIVING_ROOM,
    category: 'PLACEMENT',
    name: 'Television / Heavy Media Console in North-East',
    description:
      'Heavy electronic entertainment center is positioned in the delicate North-East corner, cluttering the mental clarity zone.',
    targetObject: 'television',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.NORTH_EAST,
    },
    severity: SeverityEnum.MEDIUM,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -10,
    defaultRemedy:
      'Shift television to the South-East or North-West wall. Keep the North-East zone open, light, and airy.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'LIV-003-TV-SE-COMPLIANT',
    roomType: RoomTypeEnum.LIVING_ROOM,
    category: 'PLACEMENT',
    name: 'Media Electronics in South-East (Agni Zone)',
    description:
      'Television and entertainment electronics placed in the South-East fire zone, naturally housing electronic energy.',
    targetObject: 'television',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.SOUTH_EAST,
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 5,
    defaultRemedy: 'Favorable electrical alignment.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'LIV-004-CHAIR-EAST-COMPLIANT',
    roomType: RoomTypeEnum.LIVING_ROOM,
    category: 'PLACEMENT',
    name: 'Light Seating / Chairs in East or North Zone',
    description:
      'Lighter seating and chairs arranged in the East or North quadrants maintain spatial lightness and allow invigorating morning solar prana to flow freely.',
    targetObject: 'chair',
    condition: {
      field: 'zone',
      op: 'IN',
      value: [DirectionEnum.EAST, DirectionEnum.NORTH, DirectionEnum.NORTH_EAST],
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 10,
    defaultRemedy: 'Auspicious living room seating arrangement.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'LIV-005-CHAIR-SW-COMPLIANT',
    roomType: RoomTypeEnum.LIVING_ROOM,
    category: 'PLACEMENT',
    name: 'Grounded Armchairs / Seating in South or West',
    description:
      'Chairs and armchairs placed along the South or West walls provide grounded stability and authority for household heads and guests.',
    targetObject: 'chair',
    condition: {
      field: 'zone',
      op: 'IN',
      value: [DirectionEnum.SOUTH_WEST, DirectionEnum.SOUTH, DirectionEnum.WEST],
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 10,
    defaultRemedy: 'Stable seating alignment.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'LIV-006-SOFA-NE-DEFECT',
    roomType: RoomTypeEnum.LIVING_ROOM,
    category: 'PLACEMENT',
    name: 'Heavy Sofa / Bulky Couch in North-East (Ishanya Defect)',
    description:
      'Heavy living room couches or bulky seating placed in the sacred North-East (Ishanya) corner clutter the mental clarity zone and block divine solar flow.',
    targetObject: 'sofa',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.NORTH_EAST,
    },
    severity: SeverityEnum.HIGH,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -15,
    defaultRemedy:
      'Shift heavy sofa set to the South or South-West wall. Keep the North-East zone open or furnished with light items only.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'LIV-007-SOFA-NW-COMPLIANT',
    roomType: RoomTypeEnum.LIVING_ROOM,
    category: 'PLACEMENT',
    name: 'Guest Seating / Sofa in North-West (Vayu Zone)',
    description:
      'Living room couches or guest seating positioned in the North-West (Vayu) quadrant. Promotes hospitable, warm, and flowing social interactions.',
    targetObject: 'sofa',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.NORTH_WEST,
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 10,
    defaultRemedy:
      'Excellent guest seating alignment. Keep upholstery light and welcoming.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'LIV-008-SOFA-SE-DEFECT',
    roomType: RoomTypeEnum.LIVING_ROOM,
    category: 'PLACEMENT',
    name: 'Heavy Seating in South-East (Agni Agitation Defect)',
    description:
      'Primary family seating situated in the South-East (Agneya) fire sector. Can induce restless conversations, short tempers, and lack of relaxation.',
    targetObject: 'sofa',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.SOUTH_EAST,
    },
    severity: SeverityEnum.MEDIUM,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -10,
    defaultRemedy:
      'Relocate main sofa to the South or West wall. Use soothing cooling tones (cream, beige, light blue) on cushions.',
    remedyType: RemedyTypeEnum.ELEMENTAL,
    isActive: true,
  },
  {
    code: 'LIV-009-SOFA-CENTER-DEFECT',
    roomType: RoomTypeEnum.LIVING_ROOM,
    category: 'PLACEMENT',
    name: 'Bulky Sofa Blocking Room Center (Brahmasthan Clutter)',
    description:
      'Heavy sectional sofa placed directly in the central zone (Brahmasthan) of the living room, choking cosmic energy circulation.',
    targetObject: 'sofa',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.CENTER,
    },
    severity: SeverityEnum.HIGH,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -20,
    defaultRemedy:
      'Push seating outward against South or West walls to open the central spatial core.',
    remedyType: RemedyTypeEnum.STRUCTURAL,
    isActive: true,
  },
  {
    code: 'LIV-010-TABLE-NE-COMPLIANT',
    roomType: RoomTypeEnum.LIVING_ROOM,
    category: 'PLACEMENT',
    name: 'Light Coffee / Side Table in North or East',
    description:
      'Lightweight table arranged in the North or East quadrant, maintaining airy openness while serving functional needs.',
    targetObject: 'table',
    condition: {
      field: 'zone',
      op: 'IN',
      value: [DirectionEnum.NORTH, DirectionEnum.EAST, DirectionEnum.NORTH_EAST],
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 5,
    defaultRemedy:
      'Keep tabletop clutter-free with a small fresh flower vase.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'LIV-011-TABLE-CENTER-DEFECT',
    roomType: RoomTypeEnum.LIVING_ROOM,
    category: 'PLACEMENT',
    name: 'Heavy Center Table Overloading Brahmasthan',
    description:
      'A large, heavy, or cluttered center table occupies the core Brahmasthan of the living room, causing spatial stagnation.',
    targetObject: 'table',
    condition: {
      field: 'zone',
      op: 'EQUALS',
      value: DirectionEnum.CENTER,
    },
    severity: SeverityEnum.MEDIUM,
    verdictOnMatch: VerdictEnum.DEFECT,
    scoreImpact: -10,
    defaultRemedy:
      'Use a lightweight, low-profile, or glass-top coffee table and keep it free of permanent clutter.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
  {
    code: 'LIV-012-PLANT-NE-COMPLIANT',
    roomType: RoomTypeEnum.LIVING_ROOM,
    category: 'PLACEMENT',
    name: 'Indoor Plants in North or East (Pranic Growth)',
    description:
      'Lush indoor greenery or potted plants in the North, East, or North-East quadrants, amplifying oxygen, life prana, and positivity.',
    targetObject: 'indoor_plants',
    condition: {
      field: 'zone',
      op: 'IN',
      value: [DirectionEnum.NORTH, DirectionEnum.EAST, DirectionEnum.NORTH_EAST],
    },
    severity: SeverityEnum.LOW,
    verdictOnMatch: VerdictEnum.COMPLIANT,
    scoreImpact: 10,
    defaultRemedy:
      'Auspicious botanical placement. Ensure plants are healthy and remove dry leaves promptly.',
    remedyType: RemedyTypeEnum.DECORATIVE,
    isActive: true,
  },
];
